### ISSUE TITLE
Prisma Client Error

### ISSUE THREAD

**Issue by chduong42** [ethan0905/ft_transcendence#16]
Unable to run script :

Message: Error in Prisma Client request: 

Invalid `prisma.user.findMany()` invocation:

The table `public.users` does not exist in the current database.
  
Query:
{
  "modelName": "User",
  "operation": "findMany",
  "args": {
    "take": 100,
    "skip": 0,
    "select": {
      "id": true,
      "id42": true,
      "createdAt": true,
      "updatedAt": true,
      "email": true,
      "hash": true,
      "username": true,
      "avatarUrl": true,
      "messages": {
        "select": {
          "id": true
        }
      },
      "owner": {
        "select": {
          "id": true
        }
      },
      "admins": {
        "select": {
          "id": true
        }
      },
      "members": {
        "select": {
          "id": true
        }
      },
      "muted": {
        "select": {
          "id": true
        }
      },
      "banned": {
        "select": {
          "id": true
        }
      },
      "friends": {
        "select": {
          "friendId": true
        }
      },
      "blocked": {
        "select": {
          "blockedId": true
        }
      },
      "player1": {
        "select": {
          "id": true
        }
      },
      "player2": {
        "select": {
          "id": true
        }
      }
    }
  }
}

**Comment by ethan0905** [comment]
have you tried migrating the prisma models inside the container, as mentionned in the readme ?

**Comment by chduong42** [comment]
Yes i tryed and i meet an error

**Comment by ethan0905** [comment]
Did you try `docker exec -it backend_nestjs bash` then `npx prisma migrate dev` inside the container directly ?

**Comment by chduong42** [comment]
Ok, i success the prisma migration, but there is still a client error : 

Invalid `t=YS(this),A=Object.create()` invocation in
/mnt/nfs/homes/chduong/Desktop/ft_transcendence/backend/node_modules/prisma/prisma-client/runtime/index.js:255:7341

Can't reach database server at `postgres`:`5432`
Please make sure your database server is running at `postgres`:`5432`.

**Comment by ethan0905** [comment]
show me the logs of the docker build

**Comment by chduong42** [comment]
[10:22:09 AM] Starting compilation in watch mode...
backend_nestjs    | 
frontend_reactjs  | 
frontend_reactjs  | up to date, audited 1479 packages in 1s
frontend_reactjs  | 
frontend_reactjs  | 231 packages are looking for funding
frontend_reactjs  |   run `npm fund` for details
frontend_reactjs  | 
frontend_reactjs  | 6 high severity vulnerabilities
frontend_reactjs  | 
frontend_reactjs  | To address all issues (including breaking changes), run:
frontend_reactjs  |   npm audit fix --force
frontend_reactjs  | 
frontend_reactjs  | Run `npm audit` for details.
frontend_reactjs  | npm notice 
frontend_reactjs  | npm notice New minor version of npm available! 9.5.0 -> 9.6.1
frontend_reactjs  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
frontend_reactjs  | npm notice Run `npm install -g npm@9.6.1` to update!
frontend_reactjs  | npm notice 
frontend_reactjs  | 
frontend_reactjs  | > frontend@0.1.0 start
frontend_reactjs  | > react-scripts start
frontend_reactjs  | 
backend_nestjs    | [10:22:13 AM] Found 0 errors. Watching for file changes.
backend_nestjs    | 
backend_nestjs    | Debugger listening on ws://127.0.0.1:9229/6917ed75-bc28-423e-808b-695e6e2033b3
backend_nestjs    | For help, see: https://nodejs.org/en/docs/inspector
frontend_reactjs  | (node:38) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
frontend_reactjs  | (Use `node --trace-deprecation ...` to show where the warning was created)
frontend_reactjs  | (node:38) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
frontend_reactjs  | Starting the development server...
frontend_reactjs  | 
frontend_reactjs  | Compiled successfully!
frontend_reactjs  | 
frontend_reactjs  | You can now view frontend in the browser.
frontend_reactjs  | 
frontend_reactjs  |   Local:            http://localhost:3000
frontend_reactjs  |   On Your Network:  http://172.19.0.4:3000
frontend_reactjs  | 
frontend_reactjs  | Note that the development build is not optimized.
frontend_reactjs  | To create a production build, use npm run build.
frontend_reactjs  | 
frontend_reactjs  | webpack compiled successfully
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [NestFactory] Starting Nest application...
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [InstanceLoader] AppModule dependencies initialized +10ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [InstanceLoader] PrismaModule dependencies initialized +3ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [InstanceLoader] AuthModule dependencies initialized +1ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [InstanceLoader] UserModule dependencies initialized +0ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [RoutesResolver] AuthController {/auth}: +20ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [RouterExplorer] Mapped {/auth/signin, POST} route +2ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [RouterExplorer] Mapped {/auth, GET} route +0ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [RouterExplorer] Mapped {/auth/42, GET} route +0ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [RoutesResolver] UserController {/users}: +0ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [RouterExplorer] Mapped {/users/me, GET} route +1ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [RouterExplorer] Mapped {/users, PATCH} route +0ms
backend_nestjs    | [Nest] 32  - 03/10/2023, 10:22:14 AM     LOG [NestApplication] Nest application successfully started +1ms

**Comment by ethan0905** [comment]
did you run the `npx prisma studio` command inside the container, to be able to see the db on the `localhost:5555` port ?

**Comment by chduong42** [comment]
Ok the problem was only when we run prisma outside of the container, run inside it fix the problem. Thank you

**Comment by ethan0905** [comment]
So to conclude, your error was :
1- When you build your docker, you must go inside the backend_nestjs container and first migrate the current models (to apply them)
2- To be able to check the db, you must run the `npx prisma studio` command inside the container.
