### ISSUE TITLE
Error: Can't reach database server at `postgres`

### ISSUE THREAD

**Issue by chduong42** [ethan0905/ft_transcendence#17]
Error meet when using the following cmd :  "npx prisma migrate dev   "

== > Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "mydb", schema "public" at "postgres:5432"
Error: P1001: Can't reach database server at `postgres`:`5432`
Please make sure your database server is running at `postgres`:`5432`.

**Comment by ethan0905** [comment]
You cannot execute the migration if your docker is not built properly. Be careful with compilation errors in your backend, it can block the app running properly.

**Comment by chduong42** [comment]
Docker built and run properly
